include: [".well-known"]
theme: jekyll-theme-hacker
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
defaults:
  -
    scope:
      path: ".well-known/*"
    values:
      sitemap: false
author: zboris12
